version: '2'
services:
  redis:
    image: redis:latest
    expose:
      - "6379"
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - env
    expose:
      - "5432"
  backend:
    build: backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    links:
      - redis:redis
      - postgres:postgres
    env_file: env
    depends_on:
      - redis
      - postgres
      - frontend
  frontend:
    build: frontend/
    command: npm run start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3000:3000"

