# Generated by Django 2.0.2 on 2018-02-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encryptedprivatechat',
            options={'verbose_name': 'encrypted-private-chat'},
        ),
        migrations.AlterModelOptions(
            name='groupchat',
            options={'verbose_name': 'group-chat'},
        ),
        migrations.AlterModelOptions(
            name='privatechat',
            options={'verbose_name': 'private-chat'},
        ),
    ]
