# Generated by Django 2.0.1 on 2018-02-01 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enctyptedmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='encryptedprivatechat',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='last_message',
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='last_message',
        ),
        migrations.AddField(
            model_name='encryptedprivatechat',
            name='creation',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 2, 1, 13, 38, 44, 949842)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encryptedprivatechat',
            name='last_use',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='creation',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 2, 1, 13, 38, 55, 62170)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatechat',
            name='last_use',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enctyptedmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_set', to='chat.EncryptedPrivateChat'),
        ),
        migrations.AlterField(
            model_name='enctyptedmessage',
            name='created_at',
            field=models.TimeField(auto_created=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_set', to='chat.GroupChat'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.TimeField(auto_created=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_set', to='chat.PrivateChat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.TimeField(auto_created=True, db_index=True),
        ),
    ]
