# Generated by Django 2.0.2 on 2018-02-16 15:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20180216_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encryptedprivatechat',
            unique_together={('first_user', 'second_user')},
        ),
    ]
