# Generated by Django 2.0.1 on 2018-01-30 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180129_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(through='users.Friend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('first', 'second')},
        ),
    ]
