# Generated by Django 2.0.2 on 2018-02-22 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.FileField(help_text='Allowed type - .mp3, .wav, .ogg', upload_to='chat_audios/%y/%m/%d', validators=[django.core.validators.RegexValidator(regex='(\\.mp3|\\.wav|\\.ogg)$')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='chat_files/%y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='chat_images/%y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(help_text='Allowed type - .avi, .flv, .mwv, .mov, .mp4', upload_to='chat_videos/%y/%m/%d', validators=[django.core.validators.RegexValidator(regex='(\\.avi|\\.flv|\\.mwv|\\.mov|\\.mp4)$')])),
                ('content_type', models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'PrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'EncryptedPrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'GroupChat'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
