# Generated by Django 2.0.2 on 2018-02-22 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatvideo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatimage',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'PrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'EncryptedPrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'GroupChat'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='chatimage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatfile',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'PrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'EncryptedPrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'GroupChat'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='chatfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chataudio',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'PrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'EncryptedPrivateChat'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'chat'), ('model', 'GroupChat'), _connector='AND'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='chataudio',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
